/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooAlpha4ExpNPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooAlpha4ExpNPdf) 

 RooAlpha4ExpNPdf::RooAlpha4ExpNPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _c0,
                        RooAbsReal& _n0,
                        RooAbsReal& _c1,
                        RooAbsReal& _n1) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   c0("c0","c0",this,_c0),
   n0("n0","n0",this,_n0),
   c1("c1","c1",this,_c1),
   n1("n1","n1",this,_n1)
 { 
 } 


 RooAlpha4ExpNPdf::RooAlpha4ExpNPdf(const RooAlpha4ExpNPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   c0("c0",this,other.c0),
   n0("n0",this,other.n0),
   c1("c1",this,other.c1),
   n1("n1",this,other.n1)
 { 
 } 



 Double_t RooAlpha4ExpNPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1.0 ; 
 } 



