/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOALPHA42EXPPDF
#define ROOALPHA42EXPPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAlpha42ExpPdf : public RooAbsPdf {
public:
  RooAlpha42ExpPdf() {} ; 
  RooAlpha42ExpPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _c00,
	      RooAbsReal& _c01,
	      RooAbsReal& _frac0,
	      RooAbsReal& _c10,
	      RooAbsReal& _c11,
	      RooAbsReal& _frac1);
  RooAlpha42ExpPdf(const RooAlpha42ExpPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAlpha42ExpPdf(*this,newname); }
  inline virtual ~RooAlpha42ExpPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy c00 ;
  RooRealProxy c01 ;
  RooRealProxy frac0 ;
  RooRealProxy c10 ;
  RooRealProxy c11 ;
  RooRealProxy frac1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooAlpha42ExpPdf,1) // Your description goes here...
};
 
#endif
