/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOALPHA4EXPNPDF
#define ROOALPHA4EXPNPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAlpha4ExpNPdf : public RooAbsPdf {
public:
  RooAlpha4ExpNPdf() {} ; 
  RooAlpha4ExpNPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _c0,
	      RooAbsReal& _n0,
	      RooAbsReal& _c1,
	      RooAbsReal& _n1);
  RooAlpha4ExpNPdf(const RooAlpha4ExpNPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAlpha4ExpNPdf(*this,newname); }
  inline virtual ~RooAlpha4ExpNPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy c0 ;
  RooRealProxy n0 ;
  RooRealProxy c1 ;
  RooRealProxy n1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooAlpha4ExpNPdf,1) // Your description goes here...
};
 
#endif
