/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooAlpha4ExpTailPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooAlpha4ExpTailPdf) 

 RooAlpha4ExpTailPdf::RooAlpha4ExpTailPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _s0,
                        RooAbsReal& _a0,
                        RooAbsReal& _s1,
                        RooAbsReal& _a1) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   s0("s0","s0",this,_s0),
   a0("a0","a0",this,_a0),
   s1("s1","s1",this,_s1),
   a1("a1","a1",this,_a1)
 { 
 } 


 RooAlpha4ExpTailPdf::RooAlpha4ExpTailPdf(const RooAlpha4ExpTailPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   s0("s0",this,other.s0),
   a0("a0",this,other.a0),
   s1("s1",this,other.s1),
   a1("a1",this,other.a1)
 { 
 } 



 Double_t RooAlpha4ExpTailPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1.0 ; 
 } 



