/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooExpTailPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooExpTailPdf) 

 RooExpTailPdf::RooExpTailPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _s,
                        RooAbsReal& _a) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   s("s","s",this,_s),
   a("a","a",this,_a)
 { 
 } 


 RooExpTailPdf::RooExpTailPdf(const RooExpTailPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   s("s",this,other.s),
   a("a",this,other.a)
 { 
 } 



 Double_t RooExpTailPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1.0 ; 
 } 



