/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROO2EXPPDF
#define ROO2EXPPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Roo2ExpPdf : public RooAbsPdf {
public:
  Roo2ExpPdf() {} ; 
  Roo2ExpPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _c0,
	      RooAbsReal& _c1,
	      RooAbsReal& _frac);
  Roo2ExpPdf(const Roo2ExpPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Roo2ExpPdf(*this,newname); }
  inline virtual ~Roo2ExpPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy c0 ;
  RooRealProxy c1 ;
  RooRealProxy frac ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Roo2ExpPdf,1) // Your description goes here...
};
 
#endif
